### ISSUE TITLE
Include logs of init-containers

### ISSUE THREAD

**Issue by hsychla** [wercker/stern#68]
The output does not currently include the logs of init-containers.
Could those be added? 

Thanks for this awesome tool!

**Comment by c-knowles** [comment]
Resolved by https://github.com/wercker/stern/pull/67 if that could be merged.

**Comment by hsychla** [comment]
ah, cool, did not look into merge requests before opening this.

**Comment by prune998** [comment]
It's still not working for me (see https://github.com/wercker/stern/pull/67#issuecomment-489055221)

**Comment by prune998** [comment]
OK, I finally got it working...
I DO see the init containers logs now. sorry for the noise
